Warning, the following versions were found for django-autocomplete-light
2.2.2
2.2.1
2.2.0
2.2.0rc8
2.2.0rc7
2.2.0rc6
2.2.0rc5
2.2.0rc4
2.2.0rc3
2.2.0rc2
2.2.0rc1
2.1.1
2.1.0
2.1.0rc4
2.1.0rc3
2.1.0rc2
2.1.0rc1
2.0.9
2.0.8
2.0.7
2.0.5
2.0.4
2.0.3
2.0.2
2.0.1
2.0.0a18
2.0.0a17
2.0.0a16
2.0.0a15
2.0.0a14
2.0.0a13
2.0.0a12
2.0.0a11
2.0.0a9
2.0.0a8
2.0.0a6
2.0.0a5
2.0.0a4
2.0.0a3
2.0.0a2
2.0.0a1
1.4.14
1.4.13
1.4.12
1.4.11
1.4.10
1.4.9
1.4.8
1.4.7
1.4.6
1.4.5
1.4.4
1.4.3
1.4.2
1.4.1
1.4.0
1.3.1
1.2.6
1.2.5
1.2.4
1.2.3
1.2.2
1.2.1
1.2.0
1.1.31
1.1.30
1.1.29
1.1.28
1.1.27
1.1.26
1.1.25
1.1.24
1.1.23
1.1.22
1.1.20
1.1.19
1.1.18
1.1.17
1.1.16
1.1.15
1.1.14
1.1.13
1.1.12
1.1.11
1.1.10
1.1.9
1.1.7
1.1.6
1.1.5
1.1.4
1.1.3
1.1.2
1.1.1
1.1.0
1.0.26
1.0.25
1.0.24
1.0.23
1.0.22
1.0.21
1.0.20
1.0.19
1.0.18
1.0.17
1.0.16
1.0.15
1.0.14
1.0.13
1.0.12
1.0.11
1.0.10
1.0.9
1.0.8
1.0.6
1.0.5
1.0.4
1.0.3
1.0.2
1.0.1
1.0.0
0.8
0.7
0.7rc3
0.7rc2
0.6
0.5.2
0.5.1
0.5
0.4
0.3
0.2
0.1
Using 2.2.2
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/d/django-autocomplete-light/django-autocomplete-light-2.2.2.tar.gz (87 KB) for django-autocomplete-light.
Downloading django-autocomplete-light (use --no-download to skip this step)
Unpacking django-autocomplete-light...
done
working in /tmp/tmp8Cl7f7conda_skeleton_django-autocomplete-light-2.2.2.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages, Command
ImportError: No module named setuptools

Applying patch: '/tmp/tmp8Cl7f7conda_skeleton_django-autocomplete-light-2.2.2.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmp8Cl7f7conda_skeleton_django-autocomplete-light-2.2.2.tar.gz/django-autocomplete-light-2.2.2
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
