Warning, the following versions were found for gensim
0.11.1-1
0.11.1
0.10.3
0.10.2
0.10.1
0.10.0
0.10.0rc1
0.9.1
0.9.0
0.8.9
0.8.8
0.8.7
0.8.6
0.8.5
0.8.4
0.8.3
0.8.2
0.8.1
0.8.0
0.8.0rc1
0.7.8
0.7.7
0.7.6
0.7.5
0.7.4
0.7.3
0.7.2
0.7.1
0.7.0
0.7.0rc2
0.6.0
0.5.0
0.4.7
0.4.6
0.4.5
0.4.4
0.4.3
0.4.2
0.4.1
0.4
0.3.0
0.2
Using 0.11.1-1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/g/gensim/gensim-0.11.1-1.tar.gz (2.1 MB) for gensim.
Downloading gensim (use --no-download to skip this step)
Using cached download
Unpacking gensim...
done
working in /tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-1.3.2.tar.gz
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    ez_setup.use_setuptools()
  File "/tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 132, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 110, in _do_download
    to_dir, download_delay)
  File "/tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 290, in download_setuptools
    downloader(url, saveto)
  File "/tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 197, in download_file_curl
    _clean_check(cmd, target)
  File "/tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 160, in _clean_check
    subprocess.check_call(cmd)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', 'https://pypi.python.org/packages/source/s/setuptools/setuptools-1.3.2.tar.gz', '--silent', '--output', '/tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/setuptools-1.3.2.tar.gz']' returned non-zero exit status 77

Applying patch: '/tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpjcYGQZconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
