pyjwt not found, trying PyJWT
0
Warning, the following versions were found for PyJWT
1.3.0
1.1.0
1.0.1
1.0.0
0.4.3
0.4.2
0.4.1
Using 1.3.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/P/PyJWT/PyJWT-1.3.0.tar.gz (60 KB) for PyJWT.
Downloading PyJWT (use --no-download to skip this step)
Using cached download
Unpacking PyJWT...
done
working in /tmp/tmpsUlTRMconda_skeleton_PyJWT-1.3.0.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

The following NEW packages will be INSTALLED:

    numpy:      1.9.2-py27_0
    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-3     
    pyyaml:     3.11-py27_0 
    readline:   6.2-2       
    setuptools: 16.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    yaml:       0.1.4-0     
    zlib:       1.2.8-0     

Linking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[readline            ]|####                                              |   8%[sqlite              ]|########                                          |  16%[system              ]|############                                      |  25%[tk                  ]|################                                  |  33%[yaml                ]|####################                              |  41%[zlib                ]|#########################                         |  50%[numpy               ]|#############################                     |  58%[python              ]|#################################                 |  66%[pyyaml              ]|#####################################             |  75%[setuptools          ]|#########################################         |  83%[pip                 ]|#############################################     |  91%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpsUlTRMconda_skeleton_PyJWT-1.3.0.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/p/pep8-naming/pep8-naming-0.2.2.tar.gz (5 KB) for pep8-naming.
Downloading pep8-naming (use --no-download to skip this step)
Using cached download
Unpacking pep8-naming...
done
working in /tmp/tmpIqqMg_conda_skeleton_pep8-naming-0.2.2.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmpIqqMg_conda_skeleton_pep8-naming-0.2.2.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/f/flake8-import-order/flake8-import-order-0.6.linux-x86_64.tar.gz (14 KB) for flake8-import-order.
Downloading flake8-import-order (use --no-download to skip this step)
Using cached download
Unpacking flake8-import-order...
done
working in /tmp/tmploAzUCconda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
/home/ubuntu/miniconda/envs/_build/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory

Applying patch: '/tmp/tmploAzUCconda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmploAzUCconda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz/home
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
