Package search: {'_pypi_ordering': False, 'version': '0.8.2', 'name': 'Rtree', 'summary': 'R-Tree spatial index for Python GIS'}
Fetching package metadata: ....
Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting Rtree==0.8.2
  Downloading http://localhost/packages/source/R/Rtree/Rtree-0.8.2.tar.gz (55kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-QXFF3f/Rtree/setup.py", line 4, in <module>
        import rtree
      File "rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "rtree/index.py", line 6, in <module>
        from . import core
      File "rtree/core.py", line 110, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
        func = self.__getitem__(name)
      File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /home/ubuntu/miniconda/envs/_pipbuild_/bin/python: undefined symbol: Error_GetLastErrorNum
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QXFF3f/Rtree
Creating standard recipe for rtree-0.8.2
    LOCKERROR: It looks like conda is already doing something.
    The lock /home/ubuntu/miniconda/conda-bld/.conda_lock-26167 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 1 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock /home/ubuntu/miniconda/conda-bld/.conda_lock-26167 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 2 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock /home/ubuntu/miniconda/conda-bld/.conda_lock-26167 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 4 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock /home/ubuntu/miniconda/conda-bld/.conda_lock-26167 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 8 seconds
Using url https://pypi.python.org/packages/source/R/Rtree/Rtree-0.8.2.tar.gz (55 KB) for Rtree.
Downloading Rtree (use --no-download to skip this step)
Using cached download
Unpacking Rtree...
done
working in /tmp/tmpglTfY5conda_skeleton_Rtree-0.8.2.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import rtree
  File "/tmp/tmpglTfY5conda_skeleton_Rtree-0.8.2.tar.gz/Rtree-0.8.2/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/tmp/tmpglTfY5conda_skeleton_Rtree-0.8.2.tar.gz/Rtree-0.8.2/rtree/index.py", line 6, in <module>
    from . import core
  File "/tmp/tmpglTfY5conda_skeleton_Rtree-0.8.2.tar.gz/Rtree-0.8.2/rtree/core.py", line 110, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/ubuntu/miniconda/envs/_build/bin/python: undefined symbol: Error_GetLastErrorNum

Applying patch: '/tmp/tmpglTfY5conda_skeleton_Rtree-0.8.2.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpglTfY5conda_skeleton_Rtree-0.8.2.tar.gz/Rtree-0.8.2
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install Rtree==0.8.2
Error: Could not pip install Rtree==0.8.2
