Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-build", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 118, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 255, in execute
    m = MetaData(recipe_dir)
  File "/home/ubuntu/conda-build/conda_build/metadata.py", line 264, in __init__
    self.parse_again()
  File "/home/ubuntu/conda-build/conda_build/metadata.py", line 272, in parse_again
    self.meta = parse(get_contents(self.meta_path))
  File "/home/ubuntu/conda-build/conda_build/metadata.py", line 107, in parse
    res = yamlize(data)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/conda/utils.py", line 120, in __call__
    value = self.func(*args, **kw)
  File "/home/ubuntu/conda-build/conda_build/metadata.py", line 96, in yamlize
    return yaml.load(data)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not found expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 14, column 1:
    tox-quickstart=tox._quickstart:main
    ^
could not found expected ':'
  in "<unicode string>", line 17, column 1:
    requirements:
    ^
