Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 268, in run
    wheel_cache
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 268, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 207, in from_line
    wheel_cache=wheel_cache)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 66, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'ua-parser==[0]', 'at', '==[0]')

Package search: {'_pypi_ordering': False, 'version': '0.3.2', 'name': 'user-agents', 'summary': 'A library to identify devices (phones, tablets) and their capabilities by parsing (browser/HTTP) user agent strings'}
Creating standard recipe for user-agents-0.3.2
Converting recipe in /home/ubuntu/pypi-conda-builds/user-agents
package = user-agents
   dependencies = [u'ua-parser']
Creating standard recipe for ua-parser
Warning, the following versions were found for ua-parser
0.3.6
0.3.5
0.3.4
0.3.3
0.3.2
0.3.1
0.3.0
Using 0.3.6
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/u/ua-parser/ua-parser-0.3.6.tar.gz (36 KB) for ua-parser.
Downloading ua-parser (use --no-download to skip this step)
Using cached download
Unpacking ua-parser...
done
working in /tmp/tmpx_EdeQconda_skeleton_ua-parser-0.3.6.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Applying patch: '/tmp/tmpx_EdeQconda_skeleton_ua-parser-0.3.6.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpx_EdeQconda_skeleton_ua-parser-0.3.6.tar.gz/ua-parser-0.3.6
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install ua-parser==[0]
Error: Could not pip install ua-parser==[0]
