Warning, the following versions were found for xmltodict
0.9.2
0.9.1
0.9.0
0.8.7
0.8.6
0.8.5
0.8.4
0.8.3
0.8.2
0.8.1
0.7.0
0.6.0
0.5.1
0.5.0
0.4.6
0.4.4
0.4.3
0.4.2
0.4.1
0.4
0.3
0.2
Using 0.9.2
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/x/xmltodict/xmltodict-0.9.2.tar.gz (37 KB) for xmltodict.
Downloading xmltodict (use --no-download to skip this step)
Using cached download
Unpacking xmltodict...
done
working in /tmp/tmp6IqCZhconda_skeleton_xmltodict-0.9.2.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.6.tar.gz
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    use_setuptools()
  File "/tmp/tmp6IqCZhconda_skeleton_xmltodict-0.9.2.tar.gz/xmltodict-0.9.2/ez_setup.py", line 132, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/tmp/tmp6IqCZhconda_skeleton_xmltodict-0.9.2.tar.gz/xmltodict-0.9.2/ez_setup.py", line 110, in _do_download
    to_dir, download_delay)
  File "/tmp/tmp6IqCZhconda_skeleton_xmltodict-0.9.2.tar.gz/xmltodict-0.9.2/ez_setup.py", line 278, in download_setuptools
    downloader(url, saveto)
  File "/tmp/tmp6IqCZhconda_skeleton_xmltodict-0.9.2.tar.gz/xmltodict-0.9.2/ez_setup.py", line 185, in download_file_curl
    subprocess.check_call(cmd)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', 'https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.6.tar.gz', '--silent', '--output', '/tmp/tmp6IqCZhconda_skeleton_xmltodict-0.9.2.tar.gz/xmltodict-0.9.2/setuptools-1.1.6.tar.gz']' returned non-zero exit status 77

Applying patch: '/tmp/tmp6IqCZhconda_skeleton_xmltodict-0.9.2.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmp6IqCZhconda_skeleton_xmltodict-0.9.2.tar.gz/xmltodict-0.9.2
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
